using GRF.ContainerFormat;
using GRF.Core;
using GRF.FileFormats;
using GRF.FileFormats.ActFormat;
using GRF.FileFormats.BsonFormat;
using GRF.FileFormats.GatFormat;
using GRF.FileFormats.GndFormat;
using GRF.FileFormats.ImfFormat;
using GRF.FileFormats.LubFormat;
using GRF.FileFormats.RsmFormat;
using GRF.FileFormats.RswFormat;
using GRF.FileFormats.SprFormat;
using GRF.FileFormats.StrFormat;
using GRFEditor.ApplicationConfiguration;
using System;
using System.Text;
using Utilities.Extension;
using Utilities.Services;

namespace GRFEditor.WPF.PreviewTabs.Controls {
	public class PreviewRawStructureLoader {
		public class LoadResult {
			public bool Success;

			public bool IsReadOnly;
			public bool RawViewAvailable;
			public bool IsTextOutput;
			public bool SavingEnabled;
			public string TextOutput;
			public object ObjectOutput;
			public string Syntax;
			public Encoding EditorEncoding;
		}

		public LoadResult Load(FileEntry entry) {
			if (entry.IsRemoved) {
				throw GrfExceptions.__ThorFileDeleted.Create(entry.RelativePath);
			}
			else if (entry.IsEmpty()) {
				throw new Exception($"The file '{entry.RelativePath}' is empty (0 byte).");
			}

			switch (entry.RelativePath.GetExtension()) {
				case ".gat":
					return _loadAsPrintable(new Gat(entry));
				case ".gnd":
					return _loadAsPrintable(new Gnd(entry));
				case ".rsm":
				case ".rsm2":
					return _loadAsPrintable(new Rsm(entry));
				case ".rsw":
					return _loadAsPrintable(new Rsw(entry));
				case ".str":
					return _loadAsPrintable(new Str(entry));
				case ".fna":
					return _loadAsTextOnly(new Fna(entry));
				case ".imf":
					return _loadAsImf(entry);
				case ".act":
					return _loadAsPrintable(new Act(entry));
				case ".spr":
					return _loadAsPrintable(new Spr(entry));
				case ".lub":
					return _loadAsLub(entry);
				case ".bson":
					return _loadAsBson(entry);
				default:
					throw new Exception("There is no parser for this file.");
			}
		}

		private LoadResult _loadAsBson(FileEntry entry) {
			LoadResult result = new LoadResult();
			result.SavingEnabled = true;
			result.Syntax = "Json";
			result.EditorEncoding = EncodingService.Utf8;
			result.TextOutput = Bson.Bson2Json(entry);
			result.IsTextOutput = true;
			result.RawViewAvailable = false;
			result.IsReadOnly = false;
			return result;
		}

		private LoadResult _loadAsLub(FileEntry entry) {
			LoadResult result = new LoadResult();

			byte[] data = entry.GetDecompressedData();

			if (Lub.IsCompiled(data)) {
				Lub lub = new Lub(data);

				result.TextOutput = lub.Decompile();
				result.TextOutput = GetGrfEditorHeaderForLua() + "-- Using GRF Editor Decompiler (beta 1.1.0)\r\n\r\n" + result.TextOutput;
			}
			else {
				result.TextOutput = EncodingService.DisplayEncoding.GetString(data);
			}

			result.IsTextOutput = true;
			result.RawViewAvailable = false;
			result.Syntax = "Lua";
			return result;
		}

		private LoadResult _loadAsImf(FileEntry entry) {
			LoadResult result = _loadAsTextOnly(new Imf(entry));
			result.Syntax = "Imf";
			return result;
		}

		private LoadResult _loadAsTextOnly(IPrintable obj) {
			LoadResult result = new LoadResult();
			result.IsReadOnly = true;
			result.IsTextOutput = true;
			result.TextOutput = GetGrfEditorHeader() + obj.GetInformation();
			result.RawViewAvailable = false;
			result.Success = true;
			return result;
		}

		private LoadResult _loadAsPrintable(IPrintable obj) {
			LoadResult result = new LoadResult();
			result.IsReadOnly = true;
			result.IsTextOutput = GrfEditorConfiguration.PreviewRawFileStructure;

			if (result.IsTextOutput)
				result.TextOutput = GetGrfEditorHeader() + obj.GetInformation();
			else
				result.ObjectOutput = obj;

			result.RawViewAvailable = true;
			result.Success = true;
			return result;
		}

		public static string GetGrfEditorHeader() {
			if (!GrfEditorConfiguration.ShowGrfEditorHeader)
				return "";

			return "//\n" +
				   "//  GRF Editor [Version - " + GrfEditorConfiguration.PublicVersion + "]  [Build - " + GrfEditorConfiguration.RealVersion + "]\n" +
				   "//\n" +
				   "//  This file was generated by GRF Editor\n" +
				   "//______________________________________________________\n\n";
		}

		public static string GetGrfEditorHeaderForLua() {
			if (!GrfEditorConfiguration.ShowGrfEditorHeader)
				return "";

			return "--[[\n" +
				   "    GRF Editor [Version - " + GrfEditorConfiguration.PublicVersion + "]  [Build - " + GrfEditorConfiguration.RealVersion + "]\n" +
				   "  \n" +
				   "    This file was generated by GRF Editor\n" +
				   "--______________________________________________________]]\n\n";
		}
	}
}
